export const TECHNOLOGIES = [
	{ logo: "fa fa-brands fa-js", name: 'Javascript' },
	{ logo: 'fa-brands fa-angular', name: 'Angular' },
	{ logo: 'fa-brands fa-html5', name: 'HTML' },
	{ logo: 'fa-brands fa-css3-alt', name: 'CSS' },
	{ logo: 'fa-brands fa-sass', name: 'SaSS' },
	{ logo: 'fa-solid fa-database', name: 'SQL' },
	{ logo: 'fa-brands fa-python', name: 'Python' },
	{ logo: 'fa-brands fa-react', name: 'React' },
	{ logo: 'fa-brands fa-github', name: 'Github' },
	{ logo: 'fa-brands fa-linkedin', name: 'linkedin' },
	{ logo: 'fa-brands fa-instagram', name: 'instgram' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
	// { logo: '', name: '' },
];