export const TECHNOLOGIES = [
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
	{logo:'', name:''},
];